apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: ${{ values.component_id }}-dev
spec:
  controlPlaneRef:
    name: basic-control-plane
    namespace: istio-system